services:
  - type: web
    name: nutriai
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false
      - key: NEXT_PUBLIC_GEMINI_API_KEY
        sync: false
    healthCheckPath: /
    autoDeploy: true 