services:
  - type: web
    name: nutriai
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false
      - key: NEXT_PUBLIC_GEMINI_API_KEY
        sync: false
    healthCheckPath: /
    autoDeploy: true
    buildFilter:
      paths:
        - package.json
        - package-lock.json
        - next.config.js
        - src/**
        - public/**
    disk:
      name: next-cache
      mountPath: .next/cache
      sizeGB: 1
    nodeVersion: 18.17.0 